<template>
<UserLayout>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
  <h1>Balance</h1>
</UserLayout>
</template>

<script setup>
import UserLayout from '../../templates/UserLayout.vue';
</script>

<style lang="scss" scoped>

</style>
